(cl:defpackage katana_interpolated_ik_motion_planner-srv
  (:use )
  (:export
   "SETINTERPOLATEDIKMOTIONPLANPARAMS"
   "<SETINTERPOLATEDIKMOTIONPLANPARAMS-REQUEST>"
   "SETINTERPOLATEDIKMOTIONPLANPARAMS-REQUEST"
   "<SETINTERPOLATEDIKMOTIONPLANPARAMS-RESPONSE>"
   "SETINTERPOLATEDIKMOTIONPLANPARAMS-RESPONSE"
  ))

