; Auto-generated. Do not edit!


(in-package katana-msg)


;//! \htmlinclude JointMovementFeedback.msg.html

(defclass <JointMovementFeedback> (ros-message)
  ((feedback
    :reader feedback-val
    :initarg :feedback
    :type string
    :initform ""))
)
(defmethod serialize ((msg <JointMovementFeedback>) ostream)
  "Serializes a message object of type '<JointMovementFeedback>"
  (let ((__ros_str_len (length (slot-value msg 'feedback))))
    (write-byte (ldb (byte 8 0) __ros_str_len) ostream)
    (write-byte (ldb (byte 8 8) __ros_str_len) ostream)
    (write-byte (ldb (byte 8 16) __ros_str_len) ostream)
    (write-byte (ldb (byte 8 24) __ros_str_len) ostream))
  (map nil #'(lambda (c) (write-byte (char-code c) ostream)) (slot-value msg 'feedback))
)
(defmethod deserialize ((msg <JointMovementFeedback>) istream)
  "Deserializes a message object of type '<JointMovementFeedback>"
  (let ((__ros_str_len 0))
    (setf (ldb (byte 8 0) __ros_str_len) (read-byte istream))
    (setf (ldb (byte 8 8) __ros_str_len) (read-byte istream))
    (setf (ldb (byte 8 16) __ros_str_len) (read-byte istream))
    (setf (ldb (byte 8 24) __ros_str_len) (read-byte istream))
    (setf (slot-value msg 'feedback) (make-string __ros_str_len))
    (dotimes (__ros_str_idx __ros_str_len msg)
      (setf (char (slot-value msg 'feedback) __ros_str_idx) (code-char (read-byte istream)))))
  msg
)
(defmethod ros-datatype ((msg (eql '<JointMovementFeedback>)))
  "Returns string type for a message object of type '<JointMovementFeedback>"
  "katana/JointMovementFeedback")
(defmethod md5sum ((type (eql '<JointMovementFeedback>)))
  "Returns md5sum for a message object of type '<JointMovementFeedback>"
  "c14cdf907e5c7c7fd47292add15660f0")
(defmethod message-definition ((type (eql '<JointMovementFeedback>)))
  "Returns full string definition for message of type '<JointMovementFeedback>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%string feedback~%~%~%~%"))
(defmethod serialization-length ((msg <JointMovementFeedback>))
  (+ 0
     4 (length (slot-value msg 'feedback))
))
(defmethod ros-message-to-list ((msg <JointMovementFeedback>))
  "Converts a ROS message object to a list"
  (list '<JointMovementFeedback>
    (cons ':feedback (feedback-val msg))
))
