#!/bin/sh
rosparam load $(rospack find katana_arm_gazebo)/config/katana_finger_position_controllers.yaml

rosrun pr2_controller_manager pr2_controller_manager stop katana_r_finger_position_controller
rosrun pr2_controller_manager pr2_controller_manager unload katana_r_finger_position_controller
rosrun pr2_controller_manager pr2_controller_manager load katana_r_finger_position_controller
rosrun pr2_controller_manager pr2_controller_manager start katana_r_finger_position_controller

rosrun pr2_controller_manager pr2_controller_manager stop katana_l_finger_position_controller
rosrun pr2_controller_manager pr2_controller_manager unload katana_l_finger_position_controller
rosrun pr2_controller_manager pr2_controller_manager load katana_l_finger_position_controller
rosrun pr2_controller_manager pr2_controller_manager start katana_l_finger_position_controller

