#!/bin/sh
rosrun controller_manager controller_manager stop katana_arm_controller
rosrun controller_manager controller_manager unload katana_arm_controller
rosparam load $(rospack find katana_arm_gazebo)/config/katana_arm_controller.yaml
rosrun controller_manager controller_manager load katana_arm_controller
rosrun controller_manager controller_manager start katana_arm_controller

